services:
  - type: web
    name: github-candidate-search
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm run preview
    envVars:
      - key: VITE_GITHUB_TOKEN
        value: your_github_token_here